Update README.md
chaoss/wg-metrics-development pull request #186
Opened 2023-02-28 15:43 UTC by germonprez

Signed-off-by: Matt Germonprez <germonprez@gmail.com>

Suggesting changes to the README -- updating links, copyright and a few other things around contributions.

2023-02-28 16:58 UTC, geekygirldawn requested changes

2023-02-28 16:58 UTC, geekygirldawn commented on README.md
> +Copyright © 2023 - CHAOSS
LF Guidance is to leave the year off: https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects

We should probably change ours to be one of these for all of our projects:
* Copyright The XYZ Authors.
* Copyright The XYZ Contributors.
* Copyright Contributors to the XYZ project.

2023-03-01 11:42 UTC, germonprez commented
Thanks for this @geekygirldawn -- I'm going to wait on this for the time being so that I can first go look at the template first.

2024-10-14 19:50 UTC, ElizabethN commented
I'm doing a little repo cleanup today and I don't think this PR matches the current state of the README file, so I'm going to go ahead and close it @germonprez. If there are more changes to be made to the current README we can do that in a new PR. Sound ok?

2024-10-14 19:50 UTC, closed without merging